#!/usr/bin/env bash
# Auto-generated by Tools/portfolio_runner.sh
SOURCE_RUNNER="/home/surya/Tools/portfolio_runner.sh"
CURRENT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 && pwd)"

if [ -f "$SOURCE_RUNNER" ]; then
    exec bash "$SOURCE_RUNNER" "$CURRENT_DIR"
else
    echo "Portfolio Runner tidak ditemukan di Tools. Menjalankan fallback..."
    if [ -f "package.json" ]; then
        npm run dev
    elif [ -d "backend" ] && [ -d "frontend" ]; then
        (cd backend && uvicorn app.main:app --reload) &
        (cd frontend && npm run dev) &
        wait
    fi
fi
